// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { ConfigService } from "@nestjs/config";
import "dotenv/config";
import { defineConfig } from "prisma/config";

const config = new ConfigService();
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || config.get<string>("DATABASE_URL"),
  },
});
